car_poolers/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from . import views as view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.index, name='index'),
    url(r'^drivers/', include('drivers.urls')),
    url(r'^riders/', include('riders.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/accounts/register/'}),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

riders/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'riders'

urlpatterns = [
    url(r'^$', views.r_index,name='riderindex'),
    url(r'^about/$', views.about,name='about'),
    url(r'^profiles/(?P<username>[-_\w.]+)/$', views.profile,name='riderprofiles'),
    url(r'^profiles/edit/(?P<username>[-_\w.]+)/$', views.update_profile,name='edit'),
    url(r'^profiles/driverprofile/(\d+)/$', views.driverprofile, name='driverprofile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

riders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
import datetime as dt
from random import choices
import string as str


class RiderProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.CharField(max_length=15, blank=True)
    bio = models.TextField(max_length=255, blank=True)
    email = models.EmailField()
    phone_number = PhoneNumberField(max_length=10, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to = 'riderphotos/',blank=True,null=True)


    User.profile = property(lambda u: RiderProfile.objects.get_or_create(user=u)[0])

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:

        RiderProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):

    instance.riderprofile.save()

def generate_id():
        n = 10
        random = str.ascii_uppercase + str.ascii_lowercase + str.digits
        return ''.join(choice(random) for _ in range(n))

@property
def profile_pic_url(self):
    if self.profile_pic and hasattr(self.profile_pic, 'url'):
        return self.profile_pic.url

riders/forms.py
from django import forms
from .models import RiderProfile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = RiderProfile
        fields = ('profile_pic', 'location', 'phone_number')

        exclude = ['comment',]

riders/views.py
from __future__ import absolute_import
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.http import Http404
from .forms import UserForm,ProfileForm
from .models import RiderProfile
import datetime as dt
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from drivers.models import DriverProfile

# DEFAULT = 'static/img/default.png'

# Create your views here.
@login_required(login_url='/accounts/register/')
def r_index(request):
    return render(request, 'riders/r-index.html')

def logout(request):
    return render(request, 'riders/r-index.html')

def about(request):
    return render(request, 'about.html')

@login_required
@transaction.atomic
def update_profile(request,username):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile, files = request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect(reverse('riders:riderprofiles', kwargs = {'username': request.user.username}))
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'riders/profiles/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def profile(request,username):

    user = User.objects.get(username=username)
    driverprofile = DriverProfile.objects.all()

    try:
        riderprofile = RiderProfile.objects.get(user=user)
        print(riderprofile)
    except ObjectDoesNotExist:
        raise Http404()

    return render(request, 'riders/profiles/profile.html', {"user":user, "riderprofile":riderprofile})

def driverprofile(request,driverprofile_id):
    user= User.objects.get(id = driverprofile_id)
    if user:
        driverprofile = DriverProfile.objects.get(user=user)
        return render(request,'drivers/profiles/driverprofile.html',{"driverprofile": driverprofile})

riders/templates/riders/about.html
{% extends 'base.html'%} {% load bootstrap3 %} {% load staticfiles %}
<!-- block content -->
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Anywhere, Anytime</h2><br>
      <p>Whether it's Late night drinks, running errands, daily commute or catching a flight,<strong> Count on PMR.</strong>
      </p>
    </div>
    <div class="col-md-6">
      <h2>About</h2><br>
      <p>This is a car pooling system that helps users get around easily. <br> When the car owner wants to share his/her car, they will enter the information suchas number of passengers , source/destination e.t.c <br> Any person who wants tojoin a shared
        car should enter some information such as picking point and <br> dstination point.
      </p>
    </div>
  </div>
</div>
{% endblock %}

riders/templates/riders/base.html
 {% load bootstrap3 %}{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% if title %}
    <title>Pool My Ride- {{title}}</title>
    {% else %}
    <title>Pool My Ride</title>
    {% endif %} {% block styles %} {% bootstrap_css%}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="img/png" href="{% static 'img/logo.png' %}" /> {% endblock %}
  </head>

  <body>
    {% include "riders/r-navbar.html" %} {% block content %} {% endblock %} {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %} {% endblock %}

  </body>

</html>

riders/templates/riders/r-homepage.html
{% extends 'base.html'%} { load bootstrap3 %} {% load static %}{% block content %} {% endblock %}

riders/templates/riders/r-index.html
{% extends 'riders/base.html'%} {% load bootstrap3 %} {% load staticfiles %}
<!-- block content -->
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <!-- empty div -->
    </div>
    <div class="col-md-6">
      <h2>Rider information</h2><br>
      <p></p>
    </div>
  </div>
</div>
{% endblock %}

riders/templates/riders/r-index_posts.html
{% extends 'riders/base.html' %}{% load bootstrap3 %} {% load static %}
<!-- content block -->
{% block content %}
<p>gvhbjklm</p>
<br> {% endblock %}

riders/templates/riders/r-navbar.html
{% load bootstrap3 %} {% load static %} {% block title %} {{title}} {% endblock %} {% block styles%} {% bootstrap_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"> {% endblock %} {% block body %}
<!-- Navigation -->
<header class="site-header navbar-transparent">
  <nav class="navbar navbar-default">
    <div class="container">

      <!-- Toggle buttons and brand -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
            <span class="glyphicon glyphicon-option-vertical"></span>
          </button>

        <button type="button" class="navbar-toggle for-sidebar" data-toggle="offcanvas">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="/"><img src="/static/img/logo.png" alt="logo" width="60"></a>
        <a class="navbar-brand" href="/accounts/register">
            <i class="/"></i>Pool My Ride
          </a>
      </div>
      <!-- END Toggle buttons and brand -->

      <!-- Top navbar -->
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="true" role="banner">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <form class="navbar-form" role="search">
              <div class="input-group has-feedback">
                <input type="text" class="form-control" placeholder="Search..">
                <i class="form-control-feedback glyphicon glyphicon-search"></i>
              </div>
            </form>
          </li>
          <!-- action="/" -->
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'riders:about'%}">About</a>
          </li>
          <!-- <li>
            <a href="/drivers/" class='btn btn-default btn-sm' id="btncolor">BECOME A DRIVER</a>
          </li> -->
          <li>
            <a href="#">{{ user.username }}</a>
          </li>
          <li>
            <a href="{% url 'riders:riderprofiles' request.user.username %}">Profile</a>
          </li>
          <li>
            <a href="{% url 'riders:edit' request.user.username  %}">Edit Profile</a>
          </li>
          <li>
            <a href="/logout">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'about'%}">About</a>
          </li>
          <li>
            <a href="/accounts/register" class='btn btn-default btn-sm' id="btncolor">BECOME A DRIVER</a>
          </li>
          <li>
            <a href="/accounts/register" class='btn btn-default btn-sm' id="btncolor">SIGN IN AS RIDER</a>
          </li>
          <li>
            <a class='btn btn-primary btn-sm' href="/accounts/login">Login</a>
          </li>
          <li></li>
          {% endif %}
        </ul>
      </div>
      <!-- END Top navbar -->
    </div>
  </nav>
  <!-- END Top navbar & branding -->

</header>
{% endblock %}