car_poolers/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from . import views as view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.index, name='index'),
    url(r'^drivers/', include('drivers.urls')),
    url(r'^riders/', include('riders.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/accounts/register/'}),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

drivers/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'drivers'

urlpatterns = [
    url(r'^$', views.d_index,name='driverindex'),
    url(r'^about/$', views.about,name='about'),
    url(r'^profiles/(?P<username>[-_\w.]+)/$', views.profile,name='driverprofile'),
    url(r'^profiles/edit/(?P<username>[-_\w.]+)/$', views.update_profile,name='edit'),
    url(r'^profiles/car/(?P<username>[-_\w.]+)/$', views.car, name='cardetails'),
    url(r'^profiles/riderprofile/(\d+)/$', views.riderprofile, name='riderprofile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

riders/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'riders'

urlpatterns = [
    url(r'^$', views.r_index,name='riderindex'),
    url(r'^about/$', views.about,name='about'),
    url(r'^profiles/(?P<username>[-_\w.]+)/$', views.profile,name='riderprofiles'),
    url(r'^profiles/edit/(?P<username>[-_\w.]+)/$', views.update_profile,name='edit'),
    url(r'^profiles/driverprofile/(\d+)/$', views.driverprofile, name='driverprofile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

riders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
import datetime as dt
from random import choices
import string as str


class RiderProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.CharField(max_length=15, blank=True)
    bio = models.TextField(max_length=255, blank=True)
    email = models.EmailField()
    phone_number = PhoneNumberField(max_length=10, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to = 'riderphotos/',blank=True,null=True)


    User.profile = property(lambda u: RiderProfile.objects.get_or_create(user=u)[0])

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:

        RiderProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):

    instance.riderprofile.save()

def generate_id():
        n = 10
        random = str.ascii_uppercase + str.ascii_lowercase + str.digits
        return ''.join(choice(random) for _ in range(n))

@property
def profile_pic_url(self):
    if self.profile_pic and hasattr(self.profile_pic, 'url'):
        return self.profile_pic.url

riders/forms.py
from django import forms
from .models import RiderProfile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = RiderProfile
        fields = ('profile_pic', 'location', 'phone_number')

        exclude = ['comment',]

riders/views.py
from __future__ import absolute_import
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.http import Http404
from .forms import UserForm,ProfileForm
from .models import RiderProfile
import datetime as dt
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from drivers.models import DriverProfile

# DEFAULT = 'static/img/default.png'

# Create your views here.
@login_required(login_url='/accounts/register/')
def r_index(request):
    return render(request, 'riders/r-index.html')

def logout(request):
    return render(request, 'riders/r-index.html')

def about(request):
    return render(request, 'about.html')

@login_required
@transaction.atomic
def update_profile(request,username):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile, files = request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect(reverse('riders:riderprofiles', kwargs = {'username': request.user.username}))
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'riders/profiles/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def profile(request,username):

    user = User.objects.get(username=username)
    driverprofile = DriverProfile.objects.all()

    try:
        riderprofile = RiderProfile.objects.get(user=user)
        print(riderprofile)
    except ObjectDoesNotExist:
        raise Http404()

    return render(request, 'riders/profiles/profile.html', {"user":user, "riderprofile":riderprofile})

def driverprofile(request,driverprofile_id):
    user= User.objects.get(id = driverprofile_id)
    if user:
        driverprofile = DriverProfile.objects.get(user=user)
        return render(request,'drivers/profiles/driverprofile.html',{"driverprofile": driverprofile})

riders/templates/riders/profiles/base.html
{% load bootstrap3 %}{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% if title %}
    <title>Pool My Ride- {{title}}</title>
    {% else %}
    <title>Pool My Ride</title>
    {% endif %} {% block styles %} {% bootstrap_css%}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="img/png" href="{% static 'img/logo.png' %}" /> {% endblock %}
  </head>

  <body>
    {% include "riders/r-navbar.html" %} <br>
    <hr> {% block content %} {% endblock %} {% block scripts %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDk2_oVz-kMc1rXJB5nOJB_ChdhBaet9UY&callback=initMap"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/ridermap.js' %}"></script>
    {% bootstrap_javascript %} {% endblock %}

  </body>

</html>

riders/templates/riders/profiles/driverprofile.html
{% extends 'drivers/profiles/base.html' %} {% load bootstrap3 %} {% load static %} {% load ratings %}{% block content %} <br>
<div class="container" id="editprofiles">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <img src="{{driverprofile.profile_pic.url}}" class="img-responsive" alt="Image">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <h4>Username: {{user.username}}</h4>
      <h4>{{ driverprofile.phone_number}} {{user.email}}</h4>
      <h5><a href="{% url 'drivers:edit' request.user.username %}">Edit Profile</a></h5>
      <a href="{% url 'drivers:cardetails' request.user.username %}"><button class="btn btn-info">Car Details</button></a>
    </div>
    <!-- rate driver -->
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <h3>Reviews</h3> {% ratings driverprofile %}
      <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
      <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <h3>List Of Drivers</h3> {% for rider in riderprofile%}
      <ul style="list-style-type:circle">
        <li><a href="{% url 'drivers:riderprofile' rider.user.id %}"> {{rider.user.username}}</a></li>
      </ul>{% endfor%}
    </div> <br>
  </div>
  <hr>
  <!-- Display Map -->
  <div id="map">
  </div>
</div>
{% endblock %}

riders/templates/riders/profiles/edit_profile.html
{% extends 'riders/profiles/base.html' %}{% load bootstrap3 %} {% load static %} {% block content %} <br>
<div class="container" id="editprofiles">
  <div class="row">
    <div class="col-md-4">
      <ul style="list-style-type:none">
        <li><a href="/accounts/password/change">Change Password</a></li><br>
        <li>Authorized Applications</li> <br>
        <li>Comments</li><br>
        <li>Email and SMS</li><br>
        <li>Manage Contacts</li><br>
      </ul>
    </div>
    <div class="col-md-4">
      <a href="/profiles"><h2 class="btn text-center">{{user.username}}</h2></a>
      <hr>
      <form action="{% url 'riders:edit' user.username%}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {% bootstrap_form user_form %} {% bootstrap_form profile_form %}
        <button type="submit" class='btn btn-primary'>Save changes</button>
      </form>
    </div>
    <!-- empty div -->
    <div class="col-md-2"></div>
  </div>
</div>
{% endblock %}

riders/templates/riders/profiles/likers.html
<div class="modal fade" id="{{ post.slug }}_likers_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Likers</h4>
      </div>
      <div class="modal-body">
        {% for liker in posts.liker %}
        <a href="{% url 'accounts:profiles' liker.username %}"><h1>{{ liker.username }}</h1></a> {% endfor %}
      </div>
    </div>
  </div>
</div>

riders/templates/riders/profiles/post.html
{% extends 'riders/profiles/base.html' %}{% load bootstrap3 %} {% load static %} {% block content %} <br>
<div class="container" id="editprofiles">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <h3 class="btn text-center">{{user.username}}</h3>
      <hr>
      <form action="{% url 'uploadpost' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ post_form.as_p }}
        <button type="submit" class='btn btn-primary'>Upload Post</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

riders/templates/riders/profiles/profile.html
{% extends 'riders/profiles/base.html' %} {% load bootstrap3 %} {% load static %} {% load ratings %}{% block content %} <br>
<div class="container" id="editprofiles">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <img src="{{riderprofile.profile_pic.url}}" class="img-responsive" alt="Image">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <h2>Username: {{user.username}}</h2> <br>
      <h4>{{ riderprofile.phone_number}} {{user.email}}</h4>
      <h5><a href="{% url 'riders:edit' request.user.username %}">Edit Profile</a></h5>
    </div>
    <!-- rate driver -->
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <h3>Review Rider</h3> {% ratings riderprofile %}
      <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
      <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">

  </div>
  <hr>
  <!-- Display Map -->
  <div id="map">
  </div>
</div>
{% endblock %}

riders/templates/riders/profiles/update_profilepic.html
{% extends 'riders/profiles/base.html' %}{% load bootstrap3 %} {% load static %} {% block content %} <br>
<div class="container" id="editprofiles">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <h3 class="btn text-center">{{user.username}}</h3>
      <hr>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {% bootstrap_form form %}
        <button type="submit" class='btn btn-primary'>Upload Profile Picture </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}