car_poolers/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from . import views as view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.index, name='index'),
    url(r'^drivers/', include('drivers.urls')),
    url(r'^riders/', include('riders.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/accounts/register/'}),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

drivers/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'drivers'

urlpatterns = [
    url(r'^$', views.d_index,name='driverindex'),
    url(r'^about/$', views.about,name='about'),
    url(r'^profiles/(?P<username>[-_\w.]+)/$', views.profile,name='driverprofile'),
    url(r'^profiles/edit/(?P<username>[-_\w.]+)/$', views.update_profile,name='edit'),
    url(r'^profiles/car/(?P<username>[-_\w.]+)/$', views.car, name='cardetails'),
    url(r'^profiles/riderprofile/(\d+)/$', views.riderprofile, name='riderprofile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

riders/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'riders'

urlpatterns = [
    url(r'^$', views.r_index,name='riderindex'),
    url(r'^about/$', views.about,name='about'),
    url(r'^profiles/(?P<username>[-_\w.]+)/$', views.profile,name='riderprofiles'),
    url(r'^profiles/edit/(?P<username>[-_\w.]+)/$', views.update_profile,name='edit'),
    url(r'^profiles/driverprofile/(\d+)/$', views.driverprofile, name='driverprofile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

drivers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
import datetime as dt
from random import choices
import string as str

class DriverProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=255, blank=True)
    email = models.EmailField()
    phone_number = PhoneNumberField(max_length=10, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True)
    profile_pic = models.ImageField(upload_to = 'driverphotos/',blank=True)
    # cardetails = models.ForeignKey(CarDetails, on_delete=models.CASCADE)


    User.profile = property(lambda u: DriverProfile.objects.get_or_create(user=u)[0])

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:

        DriverProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):

    instance.profile.save()

def generate_id():
        n = 10
        random = str.ascii_uppercase + str.ascii_lowercase + str.digits
        return ''.join(choice(random) for _ in range(n))

class CarDetails(models.Model):
    make_of_car = models.CharField(max_length=255, blank=False)
    plates_number = models.CharField(max_length=10, blank=False)
    car_model = models.CharField(max_length=255, blank=False)
    color = models.CharField(max_length=10,blank=False)
    no_of_seats = models.IntegerField(blank=False)
    picture = models.ImageField(upload_to = 'driverphotos/',blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.make_of_car + " " + self.car_model + " belonging to " + self.user.username


class CarSharing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.CharField(max_length=255, blank=False, )
    destination = models.CharField(max_length=255, blank=False)
    cost = models.IntegerField(blank=False)
    post_date = models.DateTimeField(auto_now_add = True)
    start_time = models.TimeField(max_length=255, blank=False)
    arrival_time = models.TimeField(max_length=255, blank=False)
    no_passengers = models.IntegerField(blank=False)
    ride_details = models.TextField(blank=False)
    cardetails = models.ForeignKey(CarDetails, on_delete=models.CASCADE)
    sharing_ended = models.BooleanField(default=False)

    def __str__(self):
        return self.start + " to " + self.destination

    def get_user(self):
        return self.user


class Request(models.Model):
    carsharing = models.ForeignKey(CarSharing, on_delete=models.CASCADE)
    pick_up_point = models.CharField(max_length=255, blank=False, )
    destination = models.CharField(max_length=255, blank=False)
    register_date = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    estimated_cost = models.IntegerField(blank=False)
    status = models.CharField(max_length=255, blank=False, default='pending')

    def __str__(self):
        return self.pick_up_point

# class DriverProfile(models.Model):
#     driver = models.OneToOneField(User, on_delete=models.CASCADE)
#     profile_pic = models.ImageField('photos/', blank=False)
#     current_location = models.CharField(max_length=100, blank=False)
#     destination = models.CharField(max_length=100,blank=False)

drivers/forms.py
from django import forms
from .models import DriverProfile,Request,CarSharing,CarDetails
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = DriverProfile
        fields = ('profile_pic', 'bio', 'location', 'phone_number')

        exclude = ['comment',]

class RequestRideForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('destination','pick_up_point')

class CarSharingForm(forms.ModelForm):
    class Meta:
        model = CarSharing
        fields =('start','destination','start_time','arrival_time')

class CarDetailsForm(forms.ModelForm):
    class Meta:
        model = CarDetails
        fields =('make_of_car','plates_number','car_model','color','picture')

drivers/views.py
from __future__ import absolute_import
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.http import Http404
from .forms import UserForm,ProfileForm,RequestRideForm,CarDetailsForm
from .models import DriverProfile,Request,CarSharing,CarDetails
import datetime as dt
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from riders.models import RiderProfile

# Create your views here.
# Create your views here.
@login_required(login_url='/accounts/register/')
def d_index(request):
    return render(request, 'drivers/d-index.html')

def logout(request):
    return render(request, 'drivers/d-index.html')

def about(request):
    return render(request, 'about.html')

@login_required
@transaction.atomic
def update_profile(request,username):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile, files = request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect(reverse('drivers:driverprofile', kwargs = {'username': request.user.username}))
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'drivers/profiles/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def profile(request,username):

    user = User.objects.get(username=username)
    riderprofile = RiderProfile.objects.all()

    try:
        driverprofile = DriverProfile.objects.get(user=user)
        print(driverprofile)
    except ObjectDoesNotExist:
        raise Http404()

    return render(request, 'drivers/profiles/profile.html', {"user":user, "driverprofile":driverprofile, "riderprofile":riderprofile})


# VEHICLE
@login_required
def car(request,username):
    user = User.objects.get(username=username)

    try:
        cardetails = CarDetails.objects.filter(user=user).all()
        print(cardetails)
    except ObjectDoesNotExist:
        raise Http404()


    return render(request, 'drivers/vehicle/car_details.html', {"user":user, "cardetails":cardetails})



@login_required
def car_details(request,username):

    user = User.objects.get(username=username)
    try:
        if request.method == 'POST':
            car_form = CarDetailsForm(request.POST, files=request.FILES)
            if car_form.is_valid():
                single_car = car_form.save(commit=False)
                single_car.save()
                return redirect(reverse('drivers:cardetails', kwargs = {'username': request.user.username}))
            else:
                car_form = CarDetailsForm()
                print(car_form)
                return render(request, 'drivers/vehicle/car_details.html', {"user":user,"car_form":car_form})
        else:
            car_form = CarDetailsForm()
            return render(request, 'drivers/vehicle/car_details.html', {"user":user,"car_form":car_form})

    except ObjectDoesNotExist:

        raise Http404()


@login_required
def carshare(request,user_id):
    user = User.objects.get(pk=user_id)
    form = CarSharing(request.POST)
    #
    # if user.user.type == 'Rider':
    #     raise Http404
    carsharing = CarDetails.objects.get(pk=cardetails_id, user=user)

    if request.method == 'POST':
        if form.is_valid():
            share = form.save(commit=False)
            share.user = user

            share.start_time = request.POST['start_time']
            share.cardetails = carsharing
            share.save()

            rides = CarDetails.objects.filter(user=user).order_by('pk').reverse()
            shared = CarSharing.objects.filter(user=user).order_by('date').reverse()
            share = CarSharing.objects.filter(user=user).latest('pk')

            return render(request,'drivers/vehicle/view_share.html')

        else:
            return render(request,'drivers/vehicle/share_ride.html', {"user":user, "carsharing":carsharing, "form":form})

    else:
        return render(request,'vehicle/share_ride.html', {"user":user, "carsharing":carsharing, "form":form})

@login_required
def see_car_shared(request,user_id):
    user = User.objects.get(pk=user_id)

    # if user.user.type == 'Rider':
    #     raise Http404
    rides = CarDetails.objects.filter(user=user).order_by('pk').reverse()
    shared = CarSharing.objects.filter(user=user).order_by('date').reverse()
    request = Request.objects.filter(carsharing=shared)

    return render(request, 'drivers/vehicle/view_share.html')

@login_required
def request_ride(request,user_id,carsharing_id):
    user = User.objects.get(pk=user_id)
    carsharing = CarSharing.objects.get(pk=carsharing_id)
    form = RequestRideForm(request.POST)

    if request.method == 'POST':
        if form.is_valid():
            car_request = form.save(commit=False)
            car_request.user = user
            car_request.save()

            return redirect('d_index',user_id)

@login_required
def view_single_ride(request,carsharing_id):
    carsharing = CarSharing.objects.get(pk=carsharing_id)

    return render(request, 'drivers/vehicle/view_one_ride.html', {"carsharing":carsharing})

@login_required
def view_single_vehicle(reuqest,carsharing_id):
    carsharing = CarDetails.objects.get(pk=carsharing_id)
    return render(request, 'drivers/vehicle/view_car.html', {"carsharing":carsharing})

def riderprofile(request,riderprofile_id):
    user= User.objects.get(id = riderprofile_id)
    if user:
        riderprofile = RiderProfile.objects.get(user=user)
        return render(request,'drivers/profiles/riderprofile.html',{"riderprofile": riderprofile})

drivers/templates/drivers/about.html
{% extends 'base.html'%} {% load bootstrap3 %} {% load staticfiles %}
<!-- block content -->
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Anywhere, Anytime</h2><br>
      <p>Whether it's Late night drinks, running errands, daily commute or catching a flight,<strong> Count on PMR.</strong>
      </p>
    </div>
    <div class="col-md-6">
      <h2>About</h2><br>
      <p>This is a car pooling system that helps users get around easily. <br> When the car owner wants to share his/her car, they will enter the information suchas number of passengers , source/destination e.t.c <br> Any person who wants tojoin a shared
        car should enter some information such as picking point and <br> dstination point.
      </p>
    </div>
  </div>
</div>
{% endblock %}

drivers/templates/drivers/base.html
{% load bootstrap3 %}{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% if title %}
    <title>Pool My Ride- {{title}}</title>
    {% else %}
    <title>Pool My Ride</title>
    {% endif %} {% block styles %} {% bootstrap_css%}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="img/png" href="{% static 'img/logo.png' %}" /> {% endblock %}
  </head>

  <body>
    {% include "drivers/navbar.html" %} <br>
    <hr> {% block content %} {% endblock %} {% block scripts %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDk2_oVz-kMc1rXJB5nOJB_ChdhBaet9UY&callback=initMap"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/drivermap.js' %}"></script>
    {% bootstrap_javascript %} {% endblock %}

  </body>

</html>

drivers/templates/drivers/d-homepage.html
{% extends 'base.html'%} { load bootstrap3 %} {% load static %}{% block content %} {% endblock %}

drivers/templates/drivers/d-index.html
{% extends 'drivers/base.html'%} {% load bootstrap3 %} {% load staticfiles %}
<!-- block content -->
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <!-- empty div -->
    </div>
    <div class="col-md-6">
      <h2>Driver information</h2><br>
      <p>This is a car pooling system that helps users get around easily. <br> When the car owner wants to share his/her car, they will enter the information suchas number of passengers , source/destination e.t.c <br> Any person who wants tojoin a shared
        car should enter some information such as picking point and <br> dstination point.
      </p>
    </div>
  </div>
</div>
{% endblock %}

drivers/templates/drivers/d-index_posts.html
{% extends 'base.html' %}{% load bootstrap3 %} {% load static %}
<!-- content block -->
{% block content %}
<p>gvhbjklm</p>
<br> {% endblock %}

drivers/templates/drivers/navbar.html
{% load bootstrap3 %} {% load static %} {% block title %} {{title}} {% endblock %} {% block styles%} {% bootstrap_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"> {% endblock %} {% block body %}
<!-- Navigation -->
<header class="site-header navbar-transparent">
  <nav class="navbar navbar-default">
    <div class="container">

      <!-- Toggle buttons and brand -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
            <span class="glyphicon glyphicon-option-vertical"></span>
          </button>

        <button type="button" class="navbar-toggle for-sidebar" data-toggle="offcanvas">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="/"><img src="/static/img/logo.png" alt="logo" width="60"></a>
        <a class="navbar-brand" href="/accounts/register">
            <i class="/"></i>Pool My Ride
          </a>
      </div>
      <!-- END Toggle buttons and brand -->

      <!-- Top navbar -->
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="true" role="banner">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <form class="navbar-form" role="search">
              <div class="input-group has-feedback">
                <input type="text" class="form-control" placeholder="Search..">
                <i class="form-control-feedback glyphicon glyphicon-search"></i>
              </div>
            </form>
          </li>
          <!-- action="/" -->
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'drivers:about'%}">About</a>
          </li>
          <!-- <li>
            <a href="/drivers/" class='btn btn-default btn-sm' id="btncolor">BECOME A DRIVER</a>
          </li> -->
          <li>
            <a href="#">{{ user.username }}</a>
          </li>
          <li>
            <a href="{% url 'drivers:driverprofile' request.user.username %}">Profile</a>
          </li>
          <li>
            <a href="{% url 'drivers:edit' request.user.username  %}">Edit Profile</a>
          </li>
          <li>
            <a href="/logout">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'about'%}">About</a>
          </li>
          <li>
            <a href="/accounts/register" class='btn btn-default btn-sm' id="btncolor">BECOME A DRIVER</a>
          </li>
          <li>
            <a href="/accounts/register" class='btn btn-default btn-sm' id="btncolor">SIGN IN AS RIDER</a>
          </li>
          <li>
            <a class='btn btn-primary btn-sm' href="/accounts/login">Login</a>
          </li>
          <li></li>
          {% endif %}
        </ul>
      </div>
      <!-- END Top navbar -->
    </div>
  </nav>
  <!-- END Top navbar & branding -->

</header>
{% endblock %}